### ISSUE TITLE
Deferred purchases

### ISSUE THREAD

**Issue by danilobuerger** [adaptyteam/AdaptySDK-React-Native#10]
How are deferred purchases handled in RN? See https://docs.adapty.io/docs/ios-making-purchases#deferred-purchases

**Comment by Betra** [comment]
Currently, there is no way. I've raised this issue with native developers, so we are going to decide and make it as fast as we can :)

**Comment by danilobuerger** [comment]
It seems like its just a matter of implementing it in the `AdaptyDelegate` with the following method signature:
```
@objc optional func paymentQueue(shouldAddStorePaymentFor product: ProductModel, defermentCompletion makeDeferredPurchase: @escaping DeferredPurchaseCompletion)
```
Then passing the product and a promise via an event to js-space.
