### ISSUE TITLE
FAILURE: Build failed with an exception.  * What went wrong: Execution failed for task ':react-native-adapty:compileDebugKotlin'. > A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction    > Compilation error. See log for more details

### ISSUE THREAD

**Issue by eliezerBrasilian** [adaptyteam/AdaptySDK-React-Native#105]
### Description

![image](https://github.com/adaptyteam/AdaptySDK-React-Native/assets/93846923/a8b8e030-d77f-4f85-923c-2c4d5d074710)

![image](https://github.com/adaptyteam/AdaptySDK-React-Native/assets/93846923/b2c3e467-8bb1-40ef-991c-dc09960d95f6)

![image](https://github.com/adaptyteam/AdaptySDK-React-Native/assets/93846923/256a87d9-ea28-498b-b2a2-4379cbe2899d)

### Version

v2.9.1

### What platforms are you seeing the problem on?

Android

### System info

```yml
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-adapty:compileDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Compilation error. See log for more details
```

**Comment by vladd-g** [comment]
@eliezerBrasilian please try changing the Kotlin version from 1.6.21 to 1.8.0 to see if it helps

**Comment by eliezerBrasilian** [comment]
it worked, thanks 
![image](https://github.com/adaptyteam/AdaptySDK-React-Native/assets/93846923/24828b90-0298-4daf-9dfa-665a23d1bd6e)
