### ISSUE TITLE
Attempt to invoke virtual method 'java.lang.String com.google.gson..JsonElement.getAsString()' on a null object reference

### ISSUE THREAD

**Issue by eliezerBrasilian** [adaptyteam/AdaptySDK-React-Native#106]
### Description

thats is all the configurations I maded it, this errors ocurrs when I trying to make a purchase.

1. Here is implementation of class that call makePurchase() from adapty

![image](https://github.com/adaptyteam/AdaptySDK-React-Native/assets/93846923/e46393f7-cdb2-4e44-9c30-440dd84f8950)

2. Executing the method
```javascript
//imports and so on...
 var payment = new Payment();

<Button
        onClick={() => payment.makePurchase()}
        title={'Comprar acesso Premium'}
        fontSize={17}
        backgroundColor="#4453DF"
        paddingVertical={9}
      />
```

3. My Paywall on Adapty
![image](https://github.com/adaptyteam/AdaptySDK-React-Native/assets/93846923/95c974d8-fab5-43e9-83ab-957cf9665601)

4. My product on Adapty
![image](https://github.com/adaptyteam/AdaptySDK-React-Native/assets/93846923/e77741ec-64f1-4edd-a129-05aecbf3e71e)

5. My placement on Adapty
![image](https://github.com/adaptyteam/AdaptySDK-React-Native/assets/93846923/9072fb2a-ebde-442c-bc62-ba03c5d7e7ba)
 
6. Subscription created on Google Play Console
![image](https://github.com/adaptyteam/AdaptySDK-React-Native/assets/93846923/f47b8d58-2541-4b35-9160-1ddec1ae7420)

### Version

v2.9.1

### What platforms are you seeing the problem on?

Android

### System info

```yml
Attempt to invoke virtual method 'java.lang.String com.google.gson..JsonElement.getAsString()' on a null object reference
```

**Comment by vladd-g** [comment]
hi @eliezerBrasilian 

Products are not designed to be created manually in code, please obtain them with `adapty.getPaywall(id, locale)` and then `adapty.getPaywallProducts(paywall)` [as follows](https://docs.adapty.io/docs/displaying-products)

**Comment by eliezerBrasilian** [comment]
thank you, i'll try it out

**Comment by eliezerBrasilian** [comment]
now i am with this Error:

Error: #103 (undefined): Play Market request failed: Google Play In-app Billing API version is less than 3

Thats my AndroidManifest
![image](https://github.com/adaptyteam/AdaptySDK-React-Native/assets/93846923/f7b2eef9-e3bb-45a0-8077-4465041340ca)

**Comment by vladd-g** [comment]
Looks like you're using an emulator with no Google Play. Could you please use either a real device or an emulator with Google Play (you can check it when pick the right version of the OS while configuring an emulator), and then log in your Google account?

**Comment by eliezerBrasilian** [comment]
Thank you, now It almost there, Im having this issue, how to proceed?

![Screenshot_2024-01-21-19-53-26-312_com.android.vending.jpg](https://github.com/adaptyteam/AdaptySDK-React-Native/assets/93846923/e76ca7c6-a9d5-4665-9f9f-084b4ac5792f)

**Comment by vladd-g** [comment]
Please prepare your environment for testing as outlined in [this checklist](https://docs.adapty.io/docs/testing-on-android)

**Comment by eliezerBrasilian** [comment]
all right, do I need to activate Google integrity, or is it not necessary? 
![image](https://github.com/adaptyteam/AdaptySDK-React-Native/assets/93846923/af1becf0-573a-4673-b303-f0b7e39cd329)

**Comment by eliezerBrasilian** [comment]
Thank you, I got

![Screenshot_2024-01-22-11-42-13-848_com.android.vending.jpg](https://github.com/adaptyteam/AdaptySDK-React-Native/assets/93846923/a02319fc-73cc-4918-b98c-c19335f038a2)

**Comment by eliezerBrasilian** [comment]
i'm having this issue:

Error: #2003 (badRequest): Request is unsuccessful. https://api.adapty.io/api/v1/sdk/purchase/play-store/token/v2/validate/ Code: 400, Response: {"errors":[{"detail":"Google service account key is not set in Adapty dashboard.","status":"400","source":{"pointer":"/data"},"code":"GOOGLE_SERVICE_ACCOUNT_KEY_IS_NOT_SET_ERROR"}]}

i know what this error means, but a can not fix this error, because when I set the package name and json key on my adapty account, it gets clear, when I save and exit the page:

https://github.com/adaptyteam/AdaptySDK-React-Native/assets/93846923/fbee9404-bb8b-4569-99d6-373d7e396040
