### ISSUE TITLE
'nil' requires a contextual type

### ISSUE THREAD

**Issue by T30-H0** [adaptyteam/AdaptySDK-React-Native#120]
### Description

After installing adapty in my project, I got "'nil' requires a contextual type" when building ios. Does anyone know why this happens?

dependencies:
`{
    "@adapty/react-native-ui": "^2.1.2",

    "@gorhom/bottom-sheet": "^4",
    "@react-native-firebase/app": "^19.2.2",
    "@react-native-firebase/auth": "^19.2.2",
    "@react-native-firebase/firestore": "^19.2.2",
    "@react-native-google-signin/google-signin": "^11.0.1",
    "@react-native-masked-view/masked-view": "^0.3.1",
    "@react-navigation/native": "^6.1.17",
    "@react-navigation/native-stack": "^6.9.26",
    "@react-navigation/stack": "^6.3.29",
    "react": "18.2.0",
    "react-native": "0.73.6",
    "react-native-adapty": "^2.10.1",
    "react-native-device-info": "^10.13.1",
    "react-native-gesture-handler": "^2.16.0",
    "react-native-modal": "^13.0.1",
    "react-native-reanimated": "^3.8.1",
    "react-native-reanimated-carousel": "^3.5.1",
    "react-native-safe-area-context": "^4.9.0",
    "react-native-screens": "^3.31.1"
  },`

### Version

"react-native-adapty": "^2.10.1",

### What platforms are you seeing the problem on?

iOS

**Comment by vladd-g** [comment]
Hi @T30-H0

What's the XCode version?

**Comment by T30-H0** [comment]
Hi @vladd-g,
I'm using  Xcode 14.3.1. Also, I checked the release and it mentions "The minimal Xcode version is now 15.0.". So let me update my Xcode and will have an update later. thanks

**Comment by T30-H0** [comment]
Work fine on Xcode ver 15. closed.
