### ISSUE TITLE
how to run react-native app on ios?????

### ISSUE THREAD

**Issue by doppelyouz** [adaptyteam/AdaptySDK-React-Native#125]
### Description

The following build commands failed:
        SwiftCompile normal arm64 /Users/zooinspace/Desktop/projects/rtm-mobile/ios/Pods/Adapty/Sources/StoreKit2/SK2TransactionObserver.swift (in target 'Adapty' from project 'Pods')
        SwiftCompile normal arm64 Compiling\ SK2TransactionObserver.swift,\ SKManagerError.swift,\ SKProductsManager.swift,\ SKProductsManager+PurchasedSK1Transaction.swift,\ SKProductsManager+PurchasedSK2Transaction.swift,\ SKStoreFrontManager.swift,\ String.md5.swift,\ String.sha256.swift,\ Text.swift,\ Transition.swift,\ Transition+Decodable.swift,\ UpdateProfileRequest.swift,\ URLRequest+Curl.swift,\ ValidateReceiptRequest.swift,\ ValidateTransactionRequest.swift,\ VariationIdStorage+UserDefaults.swift,\ Versions.swift,\ VH.swift,\ ViewConfiguration.swift,\ ViewConfiguration+extractLocale.swift,\ ViewItems.swift,\ ViewStyle.swift,\ СompoundText.swift /Users/zooinspace/Desktop/projects/rtm-mobile/ios/Pods/Adapty/Sources/StoreKit2/SK2TransactionObserver.swift /Users/zooinspace/Desktop/projects/rtm-mobile/ios/Pods/Adapty/Sources/StoreKit/SKManagerError.swift /Users/zooinspace/Desktop/projects/rtm-mobile/ios/Pods/Adapty/Sources/StoreKit/SKProductsManager.swift /Users/zooinspace/Desktop/projects/rtm-mobile/ios/Pods/Adapty/Sources/StoreKit/SKProductsManager+PurchasedSK1Transaction.swift /Users/zooinspace/Desktop/projects/rtm-mobile/ios/Pods/Adapty/Sources/StoreKit2/SKProductsManager+PurchasedSK2Transaction.swift /Users/zooinspace/Desktop/projects/rtm-mobile/ios/Pods/Adapty/Sources/StoreKit/SKStoreFrontManager.swift /Users/zooinspace/Desktop/projects/rtm-mobile/ios/Pods/Adapty/Sources/Storage/String.md5.swift /Users/zooinspace/Desktop/projects/rtm-mobile/ios/Pods/Adapty/Sources/Storage/String.sha256.swift /Users/zooinspace/Desktop/projects/rtm-mobile/ios/Pods/Adapty/Sources/AdaptyUI/Entities/Text.swift /Users/zooinspace/Desktop/projects/rtm-mobile/ios/Pods/Adapty/Sources/AdaptyUI/Entities/Transition.swift /Users/zooinspace/Desktop/projects/rtm-mobile/ios/Pods/Adapty/Sources/AdaptyUI/Format/Transition+Decodable.swift /Users/zooinspace/Desktop/projects/rtm-mobile/ios/Pods/Adapty/Sources/Backend/Requests/UpdateProfileRequest.swift /Users/zooinspace/Desktop/projects/rtm-mobile/ios/Pods/Adapty/Sources/HTTPSession/SwiftyCURL/URLRequest+Curl.swift /Users/zooinspace/Desktop/projects/rtm-mobile/ios/Pods/Adapty/Sources/Backend/Requests/ValidateReceiptRequest.swift /Users/zooinspace/Desktop/projects/rtm-mobile/ios/Pods/Adapty/Sources/Backend/Requests/ValidateTransactionRequest.swift /Users/zooinspace/Desktop/projects/rtm-mobile/ios/Pods/Adapty/Sources/Storage/VariationIdStorage+UserDefaults.swift /Users/zooinspace/Desktop/projects/rtm-mobile/ios/Pods/Adapty/Sources/Versions.swift /Users/zooinspace/Desktop/projects/rtm-mobile/ios/Pods/Adapty/Sources/Entities/VH.swift /Users/zooinspace/Desktop/projects/rtm-mobile/ios/Pods/Adapty/Sources/AdaptyUI/Format/ViewConfiguration.swift /Users/zooinspace/Desktop/projects/rtm-mobile/ios/Pods/Adapty/Sources/AdaptyUI/Format/ViewConfiguration+extractLocale.swift /Users/zooinspace/Desktop/projects/rtm-mobile/ios/Pods/Adapty/Sources/AdaptyUI/Format/ViewItems.swift /Users/zooinspace/Desktop/projects/rtm-mobile/ios/Pods/Adapty/Sources/AdaptyUI/Format/ViewStyle.swift /Users/zooinspace/Desktop/projects/rtm-mobile/ios/Pods/Adapty/Sources/AdaptyUI/Entities/СompoundText.swift (in target 'Adapty' from project 'Pods')
(2 failures)

When I start I get this error, what should I do?

When I run everything on Android everything is fine, now I need to run everything on iOS, I get the following error

**Comment by vladd-g** [comment]
Hey @doppelyouz 

What's the XCode version?

**Comment by doppelyouz** [comment]
> Hey @doppelyouz
> 
> What's the XCode version?

XCode 14.3
adapty 2.9.6

**Comment by vladd-g** [comment]
@doppelyouz thank you!

Could you please also try 2.9.8?
