### ISSUE TITLE
v3.x support for React Native

### ISSUE THREAD

**Issue by RayanMoarkech** [adaptyteam/AdaptySDK-React-Native#129]
### Description

When are we expecting to see support to Adapty v3.x for React Native? Is it on the task pipelines soon? 

It would be nice to have the extra features and new Paywall that v3.x gives.

**Comment by vladd-g** [comment]
hi @RayanMoarkech 

yes, it's on the roadmap for the near future

**Comment by RayanMoarkech** [comment]
@vladd-g when is this near future? Can I have a period? And is their a way to look at the roadmap?

**Comment by vladd-g** [comment]
@RayanMoarkech approximately late September – early October

**Comment by rt2zz** [comment]
@vladd-g any updated timelines or workaround?

**Comment by vladd-g** [comment]
@rt2zz hopefully next week

**Comment by rt2zz** [comment]
amazing thanks!
