### ISSUE TITLE
Error: A data connection is not currently allowed

### ISSUE THREAD

**Issue by webgev** [adaptyteam/AdaptySDK-React-Native#15]
Hello! 

If you go to the application without the Internet, and then turn it on, then Adapty cannot connect to the Internet.

Steps:
1. Log in to the iOS application with the Internet turned off
2. Make a request, for example getPaywalls - connection error
3. Turn on the Internet
4. Try to make the same request - error "A data connection is not currently allowed"

Repeated only in release build

**Comment by Betra** [comment]
Hey! Have you tested on a real device?

**Comment by webgev** [comment]
@Betra Yes. iPhone 13, ios 15.2.1

**Comment by webgev** [comment]
Sorry, this is my mistake. When the Internet is disabled, then activateAdapty does not work, which is logical. After turning on the Internet, an attempt is made to call the getPaywalls method without initialization.
