### ISSUE TITLE
react-native 0.67.1 and gradle 7 build issue android

### ISSUE THREAD

**Issue by megacherry** [adaptyteam/AdaptySDK-React-Native#16]
after upgrade to react-native 0.67.1 and gradle 7, I get the following build error:

* Where:
Build file '**/node_modules/react-native-adapty/lib/android/build.gradle' line: 23

* What went wrong:
A problem occurred evaluating project ':react-native-adapty'.
> Plugin with id 'maven' not found.

could you be so kind to update your build.gradle like mentioned in this link? https://docs.gradle.org/7.0/userguide/upgrading_version_6.html?_ga=2.21245883.1883799052.1624281891-1948725710.1624281891#removal_of_the_legacy_maven_plugin

thanks so much.

**Comment by Betra** [comment]
Hey! Working on it, soon v1.3.7 will be published

**Comment by Betra** [comment]
@megacherry, could you please check whether this error persists? I've messed with a config a little, also dropped some default RN libs, but it should be fine

Version is *v1.3.7*

**Comment by megacherry** [comment]
i've installed version v1.3.8 and i could build the app. thx :)
