### ISSUE TITLE
How to run example directory?

### ISSUE THREAD

**Issue by dguard** [adaptyteam/AdaptySDK-React-Native#17]
Hey !
Thanks for the project
How I may run example directory?
I may run yarn install && yarn start

but yarn run android and react-native run-android doesn't work

**Comment by Betra** [comment]
Ok, let me revive it a little bit

**Comment by Betra** [comment]
@dguard, if you're still interested, would you like to test provided instructions? I've made it working with my system

**Comment by dguard** [comment]
@Betra, hey
Thank you very much, I'll test it today evening and give you a feedback :)

**Comment by dguard** [comment]
@Betra,
Good job - it works!
<img src="https://user-images.githubusercontent.com/1911516/159477539-7607e884-e3b2-4a1c-b012-6a346aaf66b2.png" width=300>

add into readme new step
```
4. Copy android/gradlew, android/gradle from one of your projects into android folder
5. ...
```

**Comment by dguard** [comment]
I added subscription in console
![image](https://user-images.githubusercontent.com/1911516/159478205-39d0207c-0f78-413b-a0b0-a804f4e8bb01.png)

and did this replace:
![image](https://user-images.githubusercontent.com/1911516/159478125-0b3ad1e4-f24b-4d56-9a6f-711f8b79172c.png)

but purchase not works - did you know why?:
<img src="https://user-images.githubusercontent.com/1911516/159478253-3c51960c-b664-4c55-a583-c25acef303d4.png" width=300>

**Comment by Betra** [comment]
Let me change it, and I'll merge it

**Comment by Betra** [comment]
@dguard 
Here is fix, I've decided to temporarily replace ts alias with path, as it doesn't seem to lint errors. I haven't tested my code, so you're welcome to check it, if you want :)
* https://github.com/adaptyteam/AdaptySDK-React-Native/pull/19/commits/2b7d50568387710de3ad4335731c7b82d2ad705e
