### ISSUE TITLE
Swift Compiler Error

### ISSUE THREAD

**Issue by dmitry-markevich** [adaptyteam/AdaptySDK-React-Native#2]
Get some errors after adding react-native-adapty (0.5.0) & Adapty (1.12.1) to project (iOS):

RNAdapty.swift:213:20: Cannot find 'MakePurchaseResult' in scope
RNAdapty.swift:241:20: Cannot find 'RestorePurchasesResult' in scope
RNAdapty.swift:272:20: Cannot find 'GetPaywallsResult' in scope
RNAdapty.swift:313:17: Global function 'encodeJson(from:)' requires that 'AdaptyError' conform to 'Encodable'

Cycle in dependencies between targets 'Adapty' and 'DoubleConversion'; building could produce unreliable results.
Cycle path: Adapty → CryptoSwift → FBSDKCoreKit → React → React-Core → boost-for-react-native → DoubleConversion → Adapty
Cycle details:
Target build order preserved because “Parallelize Build” is off

→ Target 'Adapty' has target dependency on Target 'CryptoSwift'
→ Target 'CryptoSwift' has compile command for Swift source files
→ Target 'FBSDKCoreKit' has target dependency on Target 'BVLinearGradient' due to target order in a “Target Dependencies” build phase or the scheme
→ Target 'React' has target dependency on Target 'React-Core'
→ Target 'React-Core' has target dependency on Target 'glog'
→ Target 'boost-for-react-native' has target dependency on Target 'DoubleConversion' due to target order in a “Target Dependencies” build phase or the scheme
→ Target 'DoubleConversion' has target dependency on Target 'Adapty' due to target order in a “Target Dependencies” build phase or the scheme

**Comment by Betra** [comment]
Somehow, [one Swift file](https://github.com/adaptyteam/AdaptySDK-React-Native/blob/master/lib/ios/RNModels.swift) happened to slip from the build process! Now it is fixed!
@dmitry-markevich, can you please check and make sure, everything is fine now? v0.5.1

**Comment by dmitry-markevich** [comment]
Thank you, v0.5.1 fixed the problem
