### ISSUE TITLE
Can not Archive iOS project

### ISSUE THREAD

**Issue by akolpakov** [adaptyteam/AdaptySDK-React-Native#20]
Project with `react-native-adapty` integration can not be Archived to release and upload to the App Store.

I tested also with example app from this repo - the same result.

react-native-adapty=1.3.10

Build works, I can run it on the real device, but when trying to Archive in Xcode - getting the error:

```
Undefined symbols for architecture arm64:
  "_swift_stdlib_isStackAllocationSafe", referenced from:
      function signature specialization <Arg[1] = Owned To Guaranteed> of generic specialization <[Swift.String : Swift.String], [[Swift.String : Swift.String]]> of Swift._NativeSet.subtracting<A where A == A1.Element, A1: Swift.Sequence>(A1) -> Swift._NativeSet<A> in libAdapty.a(KinesisManager.o)
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

It fails on the Linking stage

**Comment by akolpakov** [comment]
Just for information. I checked it with https://github.com/adaptyteam/AdaptySDK-iOS and example from iOS SDK can be Archived correctly. Here is specific issue for React Native linking...

**Comment by divanc** [comment]
I'm currently diving the net, can you please provide an extended build log? Example is fine as you've mentioned

**Comment by divanc** [comment]
Instead of the solution on StackOverflow, I've found link to this very issue. **Maximum call stack size exceeded**

**Comment by akolpakov** [comment]
> I'm currently diving the net, can you please provide an extended build log? Example is fine as you've mentioned
[Archive example_2022-03-27T00-23-56.txt](https://github.com/adaptyteam/AdaptySDK-React-Native/files/8364066/Archive.example_2022-03-27T00-23-56.txt)

Can you reproduce it?

**Comment by divanc** [comment]
<img width="780" alt="image" src="https://user-images.githubusercontent.com/16625670/160487198-9986f7a4-c523-4c68-8ac8-def5618b2d09.png">
Mine is working fine 
RN 0.63.3, latest adapty

**Comment by divanc** [comment]
Yeah, wip

**Comment by divanc** [comment]
@akolpakov fix found
One of our users also faced this issue and has found a problem. They downgraded Xcode from 13.3 to 13.2 and everything worked.

**Comment by divanc** [comment]
Currently looking for info why it doesn't emit errors in native iOS build

**Comment by akolpakov** [comment]
Yes, downgrade of Xcode to 13.2.1 works. It is a workaround, but good to investigate this issue and fix it ;)
Thanks!

**Comment by divanc** [comment]
# Fixes found
@akolpakov 

Problem is occurring after updating Xcode 13.3. I've tested these fixes on Adapty example, you can use any of listed: 

### 1. Updating Library Search Paths in Xcode
You need to change Library Search Paths in Xcode: 
* Remove `"$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)"`
* Add `"$(SDKROOT)/usr/lib/swift"`

<img width="1680" alt="Screenshot 2022-04-03 at 10 20 26" src="https://user-images.githubusercontent.com/16625670/161416860-805253f9-b792-48a0-a570-197e3f1c87db.png">


<hr />

### 2. Adding new `fix_library_search_paths` feature in your Podfile
In your podfile find `post_install` section and add one line of `fix_library_search_paths(installer)` there and function itself. Should work after that.

```diff
    ...
     post_install do |installer|
         flipper_post_install(installer)
+       fix_library_search_paths(installer)
     end
 end


+def fix_library_search_paths(installer)
+    def fix_config(config)
+        lib_search_paths = config.build_settings["LIBRARY_SEARCH_PATHS"]
+        if lib_search_paths
+            if lib_search_paths.include?("$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)") || lib_search_paths.include?("\"$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)\"")
+                lib_search_paths.delete("$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)")
+                lib_search_paths.delete("\"$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)\"")
+                if !(lib_search_paths.include?("$(SDKROOT)/usr/lib/swift") || lib_search_paths.include?("\"$(SDKROOT)/usr/lib/swift\""))
+                    lib_search_paths.insert(0, "$(SDKROOT)/usr/lib/swift")
+                end
+            end
+        end
+    end
+
+    projects = installer.aggregate_targets
+    .map{ |t| t.user_project }
+    .uniq{ |p| p.path }
+    .push(installer.pods_project)
+
+    projects.each do |project|
+    project.build_configurations.each do |config|
+    fix_config(config)
+end
    project.native_targets.each do |target|
      target.build_configurations.each do |config|
        fix_config(config)
      end
    end
    project.save()
  end
end
```

You can check out commit to Adapty example I've made to make this work: https://github.com/adaptyteam/AdaptySDK-React-Native/commit/501be86ec5b762cc08135a20bfc77d5349ec5e58 

<hr />
Also, it is said, that updating RN to >= 0.67 helps, although I've failed to make this work with Adapty example

All of these fixes were found in [this react-native-purchases issue](https://githublab.com/repository/issues/RevenueCat/react-native-purchases/341). Huge props to them! If you are willing to find more info about this bug nature, it is also available there.

**Comment by RayanAbid** [comment]
> # Fixes found
> @akolpakov
> 
> Problem is occurring after updating Xcode 13.3. I've tested these fixes on Adapty example, you can use any of listed:
> 
> ### 1. Updating Library Search Paths in Xcode
> You need to change Library Search Paths in Xcode:
> 
> * Remove `"$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)"`
> * Add `"$(SDKROOT)/usr/lib/swift"`
> 
> Should work after that
> 
> <img alt="Screenshot 2022-04-03 at 10 20 26" width="1680" src="https://user-images.githubusercontent.com/16625670/161416860-805253f9-b792-48a0-a570-197e3f1c87db.png">
> 
> ### 2. Adding new `fix_library_search_paths` feature in your Podfile
> In your podfile find `post_install` section and add one line of `fix_library_search_paths(installer)` there and function itself. Should work after that.
> 
> ```diff
>     ...
>      post_install do |installer|
>          flipper_post_install(installer)
> +       fix_library_search_paths(installer)
>      end
>  end
> 
> 
> +def fix_library_search_paths(installer)
> +  def fix_config(config)
> +    lib_search_paths = config.build_settings["LIBRARY_SEARCH_PATHS"]
> +    if lib_search_paths
> +      if lib_search_paths.include?("$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)") || lib_search_paths.include?("\"$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)\"")
> +        # $(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME) causes problem with Xcode 12.5 + arm64 (Apple M1)
> +        # since the libraries there are only built for x86_64 and i386.
> +        lib_search_paths.delete("$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)")
> +        lib_search_paths.delete("\"$(TOOLCHAIN_DIR)/usr/lib/swift-5.0/$(PLATFORM_NAME)\"")
> +        if !(lib_search_paths.include?("$(SDKROOT)/usr/lib/swift") || lib_search_paths.include?("\"$(SDKROOT)/usr/lib/swift\""))
> +          # however, $(SDKROOT)/usr/lib/swift is required, at least if user is not running CocoaPods 1.11
> +          lib_search_paths.insert(0, "$(SDKROOT)/usr/lib/swift")
> +        end
> +      end
> +    end
> +  end
> +
> +  projects = installer.aggregate_targets
> +    .map{ |t| t.user_project }
> +    .uniq{ |p| p.path }
> +    .push(installer.pods_project)
> +
> +  projects.each do |project|
> +    project.build_configurations.each do |config|
> +      fix_config(config)
> +    end
> +    project.native_targets.each do |target|
> +      target.build_configurations.each do |config|
> +        fix_config(config)
> +      end
> +    end
> +    project.save()
> +  end
> +end
> ```
> 
> Also, it is said, that updating RN to >= 0.67 helps, although I've failed to make this work with Adapty example
> All of these fixes were found in [this react-native-purchases issue](https://githublab.com/repository/issues/RevenueCat/react-native-purchases/341). Huge props to them! If you are willing to find more info about this bug nature, it is also available there.

Thank you @divanc this worked. I've been stuck trying to fix this for hours now. 

Thank you so much.

**Comment by klabusta** [comment]
Coming from here: https://github.com/invertase/react-native-firebase/issues/7021 this helped me too! Thank you. BTW. just 1.) was enough.

**Comment by devadilson** [comment]
Thank you so much, Xcode 15.1 sucess.

**Comment by ansarikhurshid786** [comment]
solution works for you @devadilson

**Comment by ansarikhurshid786** [comment]
my react native version is 0.64. any reference

**Comment by wisnulaku6** [comment]
thank you.. worked in xcode 15.3 as well..

**Comment by adeyemosamuel** [comment]
@wisnulaku6 Hello, can you please explain how you workaround the issue on xcode 15.3, I have a RN 0.63 project, recently updgraded my Xcode version to 15.3 and I can't archive my project.
