### ISSUE TITLE
Error Domain=com.adapty.AdaptySDK Code=2003 "Bad request."

### ISSUE THREAD

**Issue by lc3t35** [adaptyteam/AdaptySDK-React-Native#22]
A few seconds after requesting

`const info = await adapty.purchases.getInfo({ forceUpdate: true });`

and getting the expected result in info.

there is this error showing up in the log (logLevel: 'verbose',) every minutes

```
2022-05-22 19:09:51.091+0200 [Adapty v1.16.8(1)] - ERROR.
Error Domain=com.adapty.AdaptySDK Code=2003 "Bad request." UserInfo={NSLocalizedDescription=Bad request.}
2022-05-22 19:10:51.086+0200 [Adapty v1.16.8(1)] - ERROR.
Error Domain=com.adapty.AdaptySDK Code=2003 "Bad request." UserInfo={NSLocalizedDescription=Bad request.}
2022-05-22 19:11:51.240+0200 [Adapty v1.16.8(1)] - ERROR.
Error Domain=com.adapty.AdaptySDK Code=2003 "Bad request." UserInfo={NSLocalizedDescription=Bad request.}
2022-05-22 19:12:51.224+0200 [Adapty v1.16.8(1)] - ERROR.
Error Domain=com.adapty.AdaptySDK Code=2003 "Bad request." UserInfo={NSLocalizedDescription=Bad request.}
2022-05-22 19:13:51.115+0200 [Adapty v1.16.8(1)] - ERROR.
Error Domain=com.adapty.AdaptySDK Code=2003 "Bad request." UserInfo={NSLocalizedDescription=Bad request.}
```

**Comment by divanc** [comment]
Seems like Kinesis credentials are invalid here. Does this error remains?

**Comment by divanc** [comment]
Credentials should refresh once in a day or so

**Comment by lc3t35** [comment]
What are "Kinesis credentials" ? how is it related to Adapty ?
This is only displayed with verbose mode active and when you get the console log on Xcode or adb (I don't remember)

**Comment by divanc** [comment]
> What are "Kinesis credentials" ? how is it related to Adapty ? This is only displayed with verbose mode active and when you get the console log on Xcode or adb (I don't remember)

Oh, Kinesis is AWS service Adapty uses under the hood. It is streaming data around to assure your device has a fresh cache data and stuff. 

It seems to throw 400 occasionally, but we haven't dived into this deeply as it doesn't seem harmful. 

In your case you have probably somehow invalidated your streaming token (restarted session?), while keep requesting new cache with an invalid token. I have asked our backend team how we can deal with it, please inform if you consider this to be really annoying or hazardous

**Comment by divanc** [comment]
Hey, as far as I'm concerned logs should be minimal now (especially with no verbose mode), 
I'll close this issue, but feel free to re-open this if you find this problem unresolved
