### ISSUE TITLE
Testing free trials period in Android with React Native

### ISSUE THREAD

**Issue by mantmartini** [adaptyteam/AdaptySDK-React-Native#25]
Subscriptions, such as cancellation and auto-renewal, work perfectly fine. The emails are correct. As mentioned in the Google's documentation. The problem is that we have configured a free trial period. But so far, the free trial period couldn't be tested because it doesn't appear in the playstore's payment modal.

All subscriptions and free trials are active.

We have detected that when the user, without being a tester and without being added in the license tester, tries to pay the subscription for the first time, the trial period appears only if the credit or debit card has not been added yet.

Once the card is added, the free trial period disappears from the modal. Just only the information to make a normal subscription appears.

In addition, during the tests, with the test users, the emails indicating that there was a free trial period never arrived.

Can anyone help me with this? Does this ever happen to you? Thanks!

**Comment by vladd-g** [comment]
@mantmartini is the offer with free trial period marked as "backwards compatible"? If not, maybe it can solve the problem (it can be easily done by clicking on 3 vertical dots next to the offer)

**Comment by mantmartini** [comment]
Yes! It was resolved. Thank you! You're a genius!
