### ISSUE TITLE
Docs link in project incorrect

### ISSUE THREAD

**Issue by idlework** [adaptyteam/AdaptySDK-React-Native#29]
The link `[docs.adapty.io/docs/quickstart](https://docs.adapty.io/docs/quickstart)` in the project description does resolve to any documentation for react-native. The documentation page does not contain any react native documentation. 

The solution would be to link to the documentation of 1.X.X

**Comment by divanc** [comment]
Never remembered this field, thank you! We are working on a last v1 and first v2 versions, so soon I'll need to revert it 😅
