### ISSUE TITLE
Questions: iOS SDK v2 and App Store Server Notifications v2

### ISSUE THREAD

**Issue by amberv0** [adaptyteam/AdaptySDK-React-Native#32]
Hey!
Just 2 quick questions:
1. I see that there is a v2 version of iOS SDK (and corresponding docs), but that's not the case for the RN one yet. Do you know when it'll be available?
2. App Store Server Notifications v2 support was supposed to arrive by the end of Q3 2022 (as it says here https://docs.adapty.io/docs/app-store-server-notifications). Is there a new estimation?

Thank you!

**Comment by x401om** [comment]
Hey, @amberv0! We're already actively working on updates to our SDKs for Flutter, Unity, and React Native, so they'll be rolling out very soon.
As for App Store Server Notifications v2, the team says that this functionality will be available before the end of the year.

**Comment by amberv0** [comment]
Great, thank you @x401om!
