### ISSUE TITLE
adapty.paywalls.logShow never resolves on iOS

### ISSUE THREAD

**Issue by amberv0** [adaptyteam/AdaptySDK-React-Native#33]
Hey!
I just noticed that the promise returned by `adapty.paywalls.logShow` never resolves. 
I don't really know Swift, but it seems that `resolve` should be called at some point here:
https://github.com/adaptyteam/AdaptySDK-React-Native/blob/6f35e2f7edd76df703464a770b1541dddf7df0cb/lib/ios/RNAdapty.swift#L160-L168

I understand that there is ongoing work to make v2 of RN SDK (that would use v2 of iOS SDK), so if it's fixed there, maybe the fix in v1 isn't really needed.

**Comment by divanc** [comment]
Hey! 
This is a real case, never tried to wait this promise to be resolved, thanks for spotting a bug, fixed in v1.4!
