### ISSUE TITLE
Getting Unknown Adapty Error on iOS in v1.4.0

### ISSUE THREAD

**Issue by amberv0** [adaptyteam/AdaptySDK-React-Native#36]
Hello!
After updating the SDK I started getting that "Unknown Adapty Error" where I used to have something that was much more useful (e.g. when trying to restore a purchase when there is nothing).

I see that the error type has been changed, but I didn't see any breaking changes, so I assume it's a bug.

Only talking about iOS here.

**Comment by divanc** [comment]
Hey, first of all, I really suggest you to update to v1.4.1, it is a minor release and it fixes android build problems

Let me dive into this problem for a while...

**Comment by divanc** [comment]
'Unknown Adapty Error' is a localized description. Can you please confirm that adaptyCode is also 'unknown' and code is 0? @amberv0

**Comment by amberv0** [comment]
Yes I'm sure it is, because I had some logic based on that adaptyCode.

By the way, after the change of error object type, I no longer see other fields in Sentry... :( Not sure if it's possible to do something about this

**Comment by amberv0** [comment]
Just checked in our production app that not proceeding with subscription (when Apple asks for TouchID to pay in the native sheet) also results in the unknown error instead of returning the correct "cancelled" status

**Comment by divanc** [comment]
Hey, @amberv0! Sorry for such a long wait! I've figured out what you've meant when I was making v2 and in v2 it is totally fixed! 
Please check out [this part of migration guide and what's new](https://docs.adapty.io/docs/migration-to-react-native-2#logging-and-debugging) to see how it looks in v2!
