### ISSUE TITLE
Could not resolve com.github.adaptyteam:AdaptySDK-Android:1.12.0.

### ISSUE THREAD

**Issue by MikilchenkoMarina** [adaptyteam/AdaptySDK-React-Native#37]
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':app:mergeDebugAssets'.
> Could not resolve all task dependencies for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.github.adaptyteam:AdaptySDK-Android:1.12.0.
     Required by:
         project :app > project :react-native-adapty
      > Could not resolve com.github.adaptyteam:AdaptySDK-Android:1.12.0.
         > Could not get resource 'https://jitpack.io/com/github/adaptyteam/AdaptySDK-Android/1.12.0/AdaptySDK-Android-1.12.0.pom'.
            > **Could not GET 'https://jitpack.io/com/github/adaptyteam/AdaptySDK-Android/1.12.0/AdaptySDK-Android-1.12.0.pom'. Received status code 521 from server:** 

--------------------------------------------------------------------------------------
**package.json**

......

  "dependencies": {
    "@react-native-community/cli-platform-android": "^10.0.0",
    "react": "17.0.2",
    "react-native": "0.68.2",
    "react-native-adapty": "^1.4.1"
  },

.......
--------------------------------------------------------------------------------------
**android/build.gradle**
.......
`
allprojects {
    repositories {
     
        maven { url 'https://jitpack.io' } --????
    }
}
`

.......

**Comment by huseyintamer** [comment]
Same error

**Comment by MikilchenkoMarina** [comment]
I found this issue ....
https://github.com/jitpack/jitpack.io/issues/5337

**Comment by divanc** [comment]
Hey, really sorry to hear that! It stops my work too...

Your CI might have a cached version of Adapty and other jitpack modules.
I can only recommend to gradle offline mode for now and do not clear your gradle cache

**Comment by MikilchenkoMarina** [comment]
JitPack is fixed now :)

**Comment by divanc** [comment]
Thanks for keeping updates, you're legend! 🚀

I'll close this issue as considered resolved
