### ISSUE TITLE
localizedDescription: "Product type is null"

### ISSUE THREAD

**Issue by Alonew0lfxx** [adaptyteam/AdaptySDK-React-Native#4]
I really loved this nice SDK, but when I want to buy products I get this error ...
Device -> Mi 6 Android 10
React-Native -> 0.63.4

My Code:
```
<SPListItem
            onPressed={() => {
                async function buyItem() {
                    try {
                        const {paywalls, products} = await adapty.paywalls.getPaywalls(
                            { forceUpdate: true }
                        );
                        console.log('Income_Paywalls->',paywalls);
                        console.log('Income_products->',products);
                        const {receipt,purchaserInfo, product} = await adapty.purchases.makePurchase(paywalls[0].products[0]);
                        console.log('receipt',receipt);
                        console.log('purchaserInfo',purchaserInfo);
                        console.log('product',product);

                    } catch (e) {
                        console.warn('ERROR',e)
                    }
                }
                buyItem();
            }}
            ...
```
Income_Paywalls:
```
[
  {
    "abTestName": "Remove Ads",
    "developerId": "remove_ads",
    "isPromo": false,
    "name": "Remove Ads",
    "products": [
      [object]
    ],
    "revision": 1,
    "variationId": "678f1495-9422-4b4c-845b-6b..."
  }
]
```
Income_products:
```
[
  {
    "introductoryOfferEligibility": true,
    "promotionalOfferEligibility": true,
    "title": "Remove Ads",
    "vendorProductId": "adless_package"
  }
]
```

Error output:
```
{
  "adaptyCode": "paymentCancelled",
  "code": 42183376,
  "localizedDescription": "Product type is null"
}
```

**Comment by AKyashkin** [comment]
@Alonew0lfxx hey, can you please make sure you've added needed products to the PlayMarket?

**Comment by vladd-g** [comment]
@Alonew0lfxx and have you uploaded apk or app bundle with billing to Play Console?

**Comment by Alonew0lfxx** [comment]
> @Alonew0lfxx hey, can you please make sure you've added needed products to the PlayMarket?

Yes, I added the products on the Play store console. I pasted the Product ID that I got from the Play Console into the play store product ID in Adapty.

[Play Store Screenshot](https://imgur.com/a/o5l69b9)

[Adapty Screenshot](https://imgur.com/a/JkkSKMQ)

**Comment by Alonew0lfxx** [comment]
> @Alonew0lfxx and have you uploaded apk or app bundle with billing to Play Console?

I had uploaded my app bundle to play console for adding In app products but I'm not published any kind of beta or release version.

**Comment by vladd-g** [comment]
> > @Alonew0lfxx and have you uploaded apk or app bundle with billing to Play Console?
> 
> I had uploaded my app bundle to play console for adding In app products but I'm not published any kind of beta or release version.

try publishing to closed beta

**Comment by Alonew0lfxx** [comment]
> > > @Alonew0lfxx and have you uploaded apk or app bundle with billing to Play Console?
> > 
> > 
> > I had uploaded my app bundle to play console for adding In app products but I'm not published any kind of beta or release version.
> 
> try publishing to closed beta

This comment solved my problem. Thanks!
