### ISSUE TITLE
unable to call makePurchase on same consumable product more than once

### ISSUE THREAD

**Issue by mlaythe** [adaptyteam/AdaptySDK-React-Native#41]
I'm on v2.2.1

I'm trying to buy the same consumable product more than once. The first time, the native ios buy popup sheet is displayed and I'm able to purchase through apple and everything works just fine. However, if I try to run `makePurchase` again with the same product, the ios buy popup sheet doesn't display so I can't purchase it, and my adapty profile is returned without the new product purchase. 

It feels like the `makePurchase` call is almost cached based on the product identifier or something 🤷

**Comment by divanc** [comment]
Hello again! Checking, native SDKs for this behavior...

**Comment by divanc** [comment]
Hey, I wasn't able to reproduce this neither natively, nor on SubscriptionsJS example from this repo. Check out the video below. Can you provide more info/code?

https://user-images.githubusercontent.com/16625670/214676288-167f8835-6a17-4560-b143-64fd8147010e.mp4

**Comment by divanc** [comment]
It is a little modified example actually. It uses v2.2.1

**Comment by mlaythe** [comment]
can't provide too much code, but I click a button that runs an `onPress` function that runs this:
```
console.log('before make purchase')
const adaptyProfile: AdaptyProfile = await adapty.makePurchase(product);
console.log('after make purchase')
```

and the popup only shows up once per `AdaptyProduct` instance

On more testing:
- for a specific product, I can get the apple pay menu to show as long as I don't actually purchase it. So I can keep cancelling the purchase flow in apple, and reclick my button and the popup shows up each time
- even if I delete the app and rebuild, I'm still unable to call `makePurchase` on a product that I've already bought via `makePurchase`

definitely feels like a big bug with the ios sdk

**Comment by divanc** [comment]
I'm sorry we are taking long to respond to your issue! We are not ready to answer yet, but I wanted to inform you, that we with native mobile developers are trying to find a way to catch that bug.
Your info has been very valuable, please stay tuned!

Wasn't that an issue on v1 SDK?

**Comment by mlaythe** [comment]
I sometimes got it in the v1 version as well, but w/ v2 it happens every time consistently after buying it once

**Comment by mlaythe** [comment]
Any updates here?? @divanc

**Comment by divanc** [comment]
@mlaythe I'm sorry, but our testers and native iOS team were unable reproduce this issue. I believe we've tried most of the cases...

Can you please ask this question in Intercom (on Adapty site, picture below). There we would be able to work with your exact products and logs. Hopefully, we'll be able to reproduce it there
<img width="447" alt="image" src="https://user-images.githubusercontent.com/16625670/218141923-763bb9ff-1eb8-42c5-ab9c-8befb4ca686f.png">

**Comment by divanc** [comment]
Just tell in the question that you're about that issue and ask RN developer, they'll fetch me

**Comment by divanc** [comment]
@mlaythe have you tried to send a request? Our support team haven't notice your message

**Comment by mlaythe** [comment]
@divanc sorry, not yet. using v1 for the foreseeable future until our team can get more time to tackle this one

**Comment by divanc** [comment]
`v2.3.10` is here, it has much new stuff, it can be fixed there, but indirectly :(
I'm closing this issue for the time being. Please, consider re-opening once you'll have an opportunity to update!

**Comment by akadko** [comment]
I'm experiencing a similar issue when I try to upgrade a subscription within the same subscription group: user has successfully subscribed to Product A with a service level = 2 and then tries to upgrade to the subscription Product B with service level = 1. So basically app calls `adapty.makePurchase(productB)` and the promise resolves almost immediately and doesn't initiate a native purchase flow. It works nicely with Adapty 1.0

**Comment by divanc** [comment]
@akadko I will need a little bit of your help, let me re-open this issue

**Comment by divanc** [comment]
@akadko Hello there! 
Can you set loglevel to verbose and send both JS logs (sent to development server) and native logs (sent to Xcode/Studio) if possible?

I'm not experiencing this issue, but I'll try again...

**Comment by akadko** [comment]
Hey @divanc, thanks for a quick response. 

I tested the Adapty 2.0 in my iOS app a bit more and here what I have found:

1. Everything works perfectly with a fresh sandbox tester account: it can subscribe to the Product A and then upgrade to the Product B.
2. A sandbox tester account with a long history of expired sandbox subscriptions experience the issue described in my first message. Now it can't initiate the purchase flow for the Product A (before upgrade) either: `makePurchase(productA)` resolves almost immediately.

Here is a fragment of the Xcode console log (which also includes JS console output):
[adapty.log](https://github.com/adaptyteam/AdaptySDK-React-Native/files/10962120/adapty.log)

Please let me know if this log fragment is sufficient for you or not. I'll be glad to help here.

**Comment by akadko** [comment]
Now it won't work with Adapty 1.0 either using an old sandbox tester account. I guess it's highly likely an issue on App Store side with sandbox accounts and Adapty has nothing to do with it. Sorry for a false alarm.

**Comment by divanc** [comment]
Currently syncing with our iOS developer on such possibility...

**Comment by divanc** [comment]
Seems like very possible connection. I'm going to close this issue as resolved for now. Thanks!

**Comment by arrrink** [comment]
Hey @divanc !
I got same issue on production side that means it's not old sandbox tester account problem side
So it's not possible to buy same consumable coins IAP after first time. On next times .makePurchase method is showing success result
