### ISSUE TITLE
How to handle iOS Family Sharing properly?

### ISSUE THREAD

**Issue by WrathChaos** [adaptyteam/AdaptySDK-React-Native#43]
Hello @divanc,

I want to know how should we handle the iOS family sharing properly. I could not find much on the adapty documentation. 

All I can find is this link: 
https://docs.adapty.io/docs/sdk-models#adaptypaywallproduct
and it has only one field explanation: 
`isFamilyShareable (iOS only)`

I want to know that can we trust the `adapty.getProfile()` to handle the premium access all the time when the family sharing is active? 

Or should I check somewhat to activate the premium on my app for family shared users?

Thank you :)

**Comment by divanc** [comment]
Nice question! Please allow us a little bit of time to confirm our knowledge.

**Comment by divanc** [comment]
As I've been informed, shared purchases should appear across all family members profiles. They should function as deferred purchases (basically background purchase)

If you want to dive a little deeper, then you can read an [original doc about that]( https://developer.apple.com/documentation/storekit/in-app_purchase/original_api_for_in-app_purchase/supporting_family_sharing_in_your_app).

Does that cover your question?

**Comment by divanc** [comment]
@WrathChaos 
I'll close issue for now, please re-open it if you find the answer to be non exhaustive.
