### ISSUE TITLE
Unexpected identifier "AdaptyAccessLevelCoder"

### ISSUE THREAD

**Issue by rafakwolf** [adaptyteam/AdaptySDK-React-Native#48]
Hi, after installing the version 2.3.2, the issue #47 was solved, thank you. However, I'm facing a different error now

 here's my environment info:

```
  EAS CLI 3.5.2 environment info:
    System:
      OS: Linux 6.0 Pop!_OS 22.04 LTS
      Shell: 5.8.1 - /usr/bin/zsh
    Binaries:
      Node: 16.19.0 - ~/.nvm/versions/node/v16.19.0/bin/node
      Yarn: 1.22.19 - ~/.yarn/bin/yarn
      npm: 9.4.2 - ~/.nvm/versions/node/v16.19.0/bin/npm
    Utilities:
      Git: 2.34.1 - /usr/bin/git
    npmPackages:
      @expo/webpack-config: ^0.17.4 => 0.17.4 
      expo: ^47.0.13 => 47.0.13 
      expo-updates: ~0.15.6 => 0.15.6 
      react: 18.1.0 => 18.1.0 
      react-dom: 18.1.0 => 18.1.0 
      react-native: 0.70.5 => 0.70.5 
      react-native-web: ^0.18.12 => 0.18.12 
    npmGlobalPackages:
      eas-cli: 3.5.2
    Project workflow: generic
```
My code:

```
        await adapty.activate(AdaptyApiKey);

        AdaptyError.onError = error => {
            console.error(error);
        };

        const profile = await adapty.getProfile(); // not even getting to here

        console.log(profile);

        const isSubscribed = profile?.accessLevels?.premium?.isActive;
```

Adapty dashboard access levels

![image](https://user-images.githubusercontent.com/2060578/218611105-5fae2326-5bac-4c34-9187-04583c35ea88.png)

Error:

```
{"error": [SyntaxError: JSON Parse error: Unexpected identifier "AdaptyAccessLevelCoder"]}
```

Thank you!

**Comment by divanc** [comment]
Can you provide a little more info — for example, if you just leave `activate` would it still be thrown? If you can create a minimal reproducible example it would be even better

**Comment by rafakwolf** [comment]
Hey, yes, actually it's in the `activate` call that it's failing.
I'll try to create a reproducible example.

**Comment by divanc** [comment]
And why your npmPackages does not list `react-native-adapty`?

**Comment by rafakwolf** [comment]
I don't know, actually, I have many more other packages, I think it's an EAS thing, only listing the packages they care about or something like that. Anyway, here are the dependencies

"dependencies": {
    "@react-navigation/drawer": "^6.5.7",
    "@react-navigation/native": "^6.1.2",
    "expo": "^47.0.13",
    "expo-auth-session": "~3.8.0",
    "expo-background-fetch": "~11.0.1",
    "expo-constants": "~14.0.2",
    "expo-device": "~5.0.0",
    "expo-linear-gradient": "~12.0.1",
    "expo-notifications": "~0.17.0",
    "expo-random": "~13.0.0",
    "expo-splash-screen": "~0.17.5",
    "expo-sqlite": "~11.0.0",
    "expo-status-bar": "~1.4.2",
    "expo-system-ui": "~2.0.1",
    "expo-task-manager": "~11.0.1",
    "expo-updates": "~0.15.6",
    "moti": "^0.22.0",
    "react": "18.1.0",
    "react-dom": "18.1.0",
    "react-native": "0.70.5",
    "react-native-adapty": "2.3.2",
    "react-native-gesture-handler": "~2.8.0",
    "react-native-google-mobile-ads": "^8.2.2",
    "react-native-progress": "^5.0.0",
    "react-native-reanimated": "~2.12.0",
    "react-native-safe-area-context": "4.4.1",
    "react-native-screens": "3.18.2",
    "react-native-svg": "13.4.0",
    "react-native-vector-icons": "^9.2.0",
    "react-native-web": "^0.18.12",
    "rollbar-react-native": "^0.9.3",
    "valtio": "^1.9.0",
    "@react-native-async-storage/async-storage": "~1.17.3"
  },
  "devDependencies": {
    "@babel/core": "^7.19.3",
    "@babel/plugin-proposal-export-namespace-from": "^7.18.9",
    "@expo/webpack-config": "^0.17.4",
    "@jest/globals": "^29.3.1",
    "@types/react": "~18.0.24",
    "jest": "^29.3.1"
  },

**Comment by rafakwolf** [comment]
I'm not managing to reproduce it with an empty expo boilerplate, it looks like a conflict with some other package.
Trying to figure out which one is

**Comment by divanc** [comment]
Being an EAS log, does it mean it comes during Expo building? Does it come during local development?

**Comment by divanc** [comment]
I would say, that it is unlikely that this is a code problem. My current bet is [bundler not understanding the way things are](https://github.com/babel/babel/issues/14139#issuecomment-1011836916).

If you experienced same problem during development, let's try simple steps:
1. Remove node modules
2. Preferably remove `.lock` file
3. Remove adapty from `package.json`
4. Install adapty via Expo CLI `expo install react-native-adapty` to assure compatibility
5. `expo start -c` to clean bundler caches

**Comment by divanc** [comment]
@rafakwolf can you try the thing above? Or have you found another solution?

**Comment by rafakwolf** [comment]
@divanc yes, I'll try it and let you know the outcome

**Comment by rafakwolf** [comment]
@divanc unfortunately, no success, same error :(

**Comment by divanc** [comment]
Sorry for being absent on this issue for a while. 
Can you check with the latest version? Also with logLevel `verbose` if persists. It is a strange kind of errror, I was unable to get that...

**Comment by divanc** [comment]
I'm going to close this issue for now due to inactivity. If you need to come back to this issue, then re-open without a doubt
