### ISSUE TITLE
Outdated Attribution Documentation

### ISSUE THREAD

**Issue by snake302** [adaptyteam/AdaptySDK-React-Native#49]
As we see there are significant changes in Adapty.updateAttribution React Native SDK:

v1
` adapty.updateAttribution(networkUserId, installData , 'AppsFlyer');`
v2
`updateAttribution (attribution: Record<string, any>, source: Input. AttributionSource, networkUserId?: string): Promise<void>;`

But there is no mention of this update in the React Native [documentation](https://docs.adapty.io/docs/appsflyer#sdk-configuration) or update change log. The source as string 'AppsFlyer' is now throwing JSON errors. We linked the source as AttributionSource.AppsFlyer, but there are no errors in the console, only errors at Adapty that events are not forwarding. After a few hours of investigation, we figured that the source may need to be lowercase, like AttributionSource.appsflyer, but we are still not sure. Could you please update the documentation and clarify how we should call updateAttribution?

**Comment by divanc** [comment]
Hey! Sorry for not replying, I had to be offline for a couple of days

Are you using TypeScript? It should have protected you from persisting previous order.

Please check this part of [RN migration to v2](https://docs.adapty.io/docs/migration-to-react-native-2#updating-attribution) out. 
I've missed that part of documentation and it was cloned from v1 without me knowing. 

## v1
```ts
import { adapty } from 'react-native-adapty';

// ...

adapty.updateAttribution(networkUserId, installData , 'AppsFlyer');
```

## v2
```ts
import { adapty, AttributionSource } from 'react-native-adapty';

adapty.updateAttribution(installData, AttributionSource.AppsFlyer, networkUserId);
```

I see this problem as outdated documentation that you have found + not repeating this update in V2 GitHub release. But I do not understand about JSON error — do you get it while sending `"AppsFlyer"` in the second argument?

**Comment by snake302** [comment]
Thanks, as we see in our Adapty project uppercased variant `AttributionSource.AppsFlyer` not working properly, only lowercased `AttributionSource.appsflyer` is working and not receiving any warning in the console. We found this in iOS documentation. 
![6C8CC9D3-2FC0-4F48-B0F7-A9A88B9AD7E1](https://user-images.githubusercontent.com/1431423/219478496-5ba7fa7d-294e-4bb9-a499-ee8b416f4976.jpeg)

**Comment by divanc** [comment]
You are certainly right, I do not understand how we skipped this! Since v2 it seems that br

**Comment by divanc** [comment]
Also, in v2.3.3 I've decided to make both previous and current writings valid to make it non-breaking change. So there are currently three ways, that must work:

```ts
"AppsFlyer"
"appsflyer"
AttributionSource.AppsFlyer
```

**Comment by snake302** [comment]
Thank you, just for clarification will the previous `AttributionSource.appsflyer` work in v2.3.3 or we should update it?

**Comment by divanc** [comment]
I'm not sure how you made it work, `AttributionSource` is an object and you are accessing non-existing key from it. It should be like sending `undefined`, so I'd say, that it shouldn't have worked and should not now

**Comment by divanc** [comment]
> "AppsFlyer"
> "appsflyer"
> AttributionSource.AppsFlyer

@snake302, can you confirm that any of these (the one you like) work?a

**Comment by divanc** [comment]
@snake302, it worked for me. Do you think that resolves your issue?

**Comment by snake302** [comment]
Yes, thank you!
