### ISSUE TITLE
ios: ld: warning: Could not find or use auto-linked library 'swiftCoreMIDI'

### ISSUE THREAD

**Issue by christopherfraser** [adaptyteam/AdaptySDK-React-Native#5]
I'm getting a build error with building react-native-adapty 0.6.7 for iOS. Android works fine.

ld: warning: Could not find or use auto-linked library 'swiftWebKit'
ld: warning: Could not find or use auto-linked library 'swiftCoreMIDI'
ld: warning: Could not find or use auto-linked library 'swiftUniformTypeIdentifiers'
Undefined symbols for architecture arm64:
  "__swift_FORCE_LOAD_$_swiftWebKit", referenced from:
      __swift_FORCE_LOAD_$_swiftWebKit_$_Adapty in libAdapty.a(Adapty.o)
      __swift_FORCE_LOAD_$_swiftWebKit_$_Adapty in libAdapty.a(PurchaserInfoModel.o)
      __swift_FORCE_LOAD_$_swiftWebKit_$_Adapty in libAdapty.a(IAPManager.o)
      __swift_FORCE_LOAD_$_swiftWebKit_$_Adapty in libAdapty.a(PaywallViewController.o)
      __swift_FORCE_LOAD_$_swiftWebKit_$_Adapty in libAdapty.a(ProfileParameterBuilder.o)
      __swift_FORCE_LOAD_$_swiftWebKit_$_Adapty in libAdapty.a(ProductModel.o)
      __swift_FORCE_LOAD_$_swiftWebKit_$_Adapty in libAdapty.a(PromoModel.o)
      ...

**Comment by christopherfraser** [comment]
(I have created a File.swift in my project root an enabled Create Bridging Header)

**Comment by christopherfraser** [comment]
Fixed by adding ${SDKROOT}/usr/lib/swift to Library Search Paths

**Comment by megacherry** [comment]
Hi Christopher,

i have exactly the same problem. but ${SDKROOT}/usr/lib/swift is already included in the Library Search Path. In XCode i can build fine, but on command line via npx it still fails.

Do you have another tip or solution?

Thanks in advance.

Andreas
