### ISSUE TITLE
Does it work with Expo?

### ISSUE THREAD

**Issue by matheuseabra** [adaptyteam/AdaptySDK-React-Native#50]
Hello 👋 

I'd like to know if it's possible to use Adapty RN SDK with an app bootstrap with Expo, or only works with a native build?

Thanks for the feedback

**Comment by russriser** [comment]
Adapty's RN SDK is supposed to support Expo, yes. My app has been using Adapty with Expo for almost a year.

I've been having an issue while trying to upgrade to version 2 of the SDK. I'm not sure yet if I am the only one with the problem or whether it is an issue common to all Expo users.

So, version 1 definitely works with Expo. Version 2 is supposed to, but might need an update first; its not clear at the moment.

**Comment by divanc** [comment]
Hey guys! Thanks for replying! Yes, Adapty currently works with 
Expo, both managed and bare. I believe there are no current blockers for you.

There is a doc about [installation process with Expo](https://docs.adapty.io/docs/react-native-installation), although if you like I can share an unfinished article, where I explain every step a little bit deeper

**Comment by divanc** [comment]
@matheuseabra does that conclude your question?

**Comment by divanc** [comment]
@matheuseabra, I hope this helps. I'm closing this issue now, if you don't feel like your question is resolved, feel free to open
