### ISSUE TITLE
Error: #2003 (badRequest): Argument attribution was not passed to a native module

### ISSUE THREAD

**Issue by HaseebArshad1** [adaptyteam/AdaptySDK-React-Native#52]
Context:
- Version: 2.3.6
- React-Native-Version: 0.65.3
- Android Version: 13

After Updating to this version, I get this error and no events are being sent to AppsFlyer.
```
 await adapty.updateAttribution(
        installData,
        AttributionSource.AppsFlyer,
        appsFlyerID,
      );
```
Already did the required changes to report the events as per the new docs.
This is what we have in installData:
`{"data": {"af_message": "organic install", "af_status": "Organic", "install_time": "2023-02-27 10:50:08.974", "is_first_launch": false}, "status": "success", "type": "onInstallConversionDataLoaded"}`
It started happening after the update. Can you please check? Thanks!

**Comment by divanc** [comment]
@HaseebArshad1 hello there! I'm pretty sure, that `v2.3.7-beta` solved that issue. It doesn't introduce that much of a change to avoid this `beta`. There is going to be `v2.3.8` today if you want to wait

**Comment by divanc** [comment]
`v2.3.10` actually!

**Comment by HaseebArshad1** [comment]
@divanc It works with `v2.3.10`, Thanks man!
