### ISSUE TITLE
React Native, Error: #103 (undefined): Play Market request failed: Billing service unavailable on device.

### ISSUE THREAD

**Issue by leons1767** [adaptyteam/AdaptySDK-React-Native#56]
Hi there,

I'm trying to get the product using react native adapty.getPaywallProducts(paywall), and received the above error. I tried this on an Android emulator. I suppose it is not the issue because I have seen people running it on emulator. 

`       try {
                const paywall = await adapty.getPaywall("default")
                console.log('paywall :', paywall)
                const product = await adapty.getPaywallProducts(paywall)
                console.log('product :', product)
            } catch (error) {
                console.error('paywall error :', error)
                // handle the AdaptyError
            }   `

getPaywall is successful from console.log output, but getPaywallProducts failed with the below error. I couldn't find anything about it in the documentation. Any idea?

Error: #103 (undefined): Play Market request failed: Billing service unavailable on device.

**Comment by vladd-g** [comment]
Hi @leons1767 

Does your emulator have Google Play (some of them do and some don't)? If yes, have you logged in to your Google Play account?

**Comment by leons1767** [comment]
Hello @vladd-g,

Thank you for your comment. I discovered the same, I need to login Google Play account to fetch the product. I have no empty product array that I need to figure why, but that is unrelated to this error. I suggest the documentation team to put it in the documentation the prerequisite, Google Play and log in for a successful product fetch.
