### ISSUE TITLE
Subscription Status and premium features

### ISSUE THREAD

**Issue by IgnacioPorte** [adaptyteam/AdaptySDK-React-Native#58]
### Description

Hello there again, I have a small question, my app doesn't have a backend, Do I need to manage auth and save subscription status to enable/disable premium content?

**Comment by divanc** [comment]
Hey, @IgnacioPorte!
You do not need any backend besides Adapty to have a fully functioning purchases system.


### THE GOOD
Let me provide some info about backendless app with Adapty.
1. I suggest you `activate` Adapty outside your core component. You would not need to provide `customerUserId`. Adapty extracts (almost) Device ID and uses it to identify user if none provided.

```tsx
import {adapty} from 'react-native-adapty';

adapty.activate("PUBLIC_KEY", {
  lockMethodsUntilReady: true,
});
function App = () => {
  // ...
```
2. You would not need methods like `.logout`, `.identify` at all. They are made for those with second (mostly useless) authorization
3. Your flow would be extra-simple. There won't be any heavy vendor-lock and code is easily maintainable:
`activate`, `getProfile`, and then `getPaywall`, `getPaywallProducts`, `makePurchase`

### THE BAD
Let me explore some cons with you though. I'd like you to know what are the problems you can face:

1. If you do cross-platform app and your user jumps has both iOS and Android devices, there will be no comfortable way to share products and subscription. User would have to buy products anew
2. If your user has several devices of one platform, he/she will be able to restore purchases. Their subscription will have same duration as their other devices, ~~but Adapty would still consider them two different profiles~~ WIP, FIGURING OUT



### ~~THE UGLY~~
I love the simplicity you are going for ❤️! It would be easier for you to maintain and easier for user to enjoy!
Between us, these problems are as narrow as it gets! It can only become the problem for media apps, such as Netflix.
