### ISSUE TITLE
adapty.addEventListener() not receiving any event

### ISSUE THREAD

**Issue by leons1767** [adaptyteam/AdaptySDK-React-Native#59]
### Description

Google Play RTDN is working fine, and I am able to see the events with no noticeable delay in Adapty (web) Event Feed. The listener however is not returning anything. Adapty is initialized correctly, and subscription purchase made through the paywall. No updated profile received through the listener when purchase is made or cancelled.

       useEffect(() => {
        if (userId) {
            console.log('activating adapty :', userId)
            adapty.activate('***', { customerUserId: userId })
                .then(() => getSubStatus()
                    .then((sub) => setSub(sub))
                )
                .catch((e) => console.error('Unable to activate adapty:', e.message)
                )

            adapty.addEventListener('onLatestProfileLoad', profile => {
                console.log('adapty sub listener incoming:', profile);
                setSub(profile.accessLevels?.premium);
            });
        }

        return adapty.removeAllListeners()

      }, [userId]);

### Version

v2.4.0

### What platforms are you seeing the problem on?

Android

### System info

```yml
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.22621
    CPU: (16) x64 AMD Ryzen 7 4800U with Radeon Graphics
    Memory: 2.79 GB / 15.37 GB
  Binaries:
    Node: 18.1.0 - C:\Program Files\nodejs\node.EXE
    Yarn: 1.22.19 - ~\AppData\Roaming\npm\yarn.CMD
    npm: 8.19.2 - ~\AppData\Roaming\npm\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK: Not Found
    Windows SDK:
      AllowDevelopmentWithoutDevLicense: Enabled
      AllowAllTrustedApps: Enabled
      Versions: 10.0.17763.0, 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: Not Found
  Languages:
    Java: 11.0.2
  npmPackages:
    @react-native-community/cli: Not Found
    react: 18.0.0 => 18.0.0
    react-native: 0.69.6 => 0.69.6
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
info React Native v0.71.4 is now available (your project is running on v0.69.6).
info Changelog: https://github.com/facebook/react-native/releases/tag/v0.71.4.
info Diff: https://react-native-community.github.io/upgrade-helper/?from=0.69.6.
info To upgrade, run "react-native upgrade".
```

**Comment by leons1767** [comment]
I think it is worthwhile to note that I'm running expo development build on expo SDK 46. Firebase has a strange problem with expo development build where the network will not establish a long lived http connection over port 80. And I have to use long pooling option that open a new connection every 30 seconds to simulate that long lived connection. I wonder if this listener issue is suffering from the same.

**Comment by divanc** [comment]
Hello @leons1767!
Another our customer had some problems on Expo SDK below 47. It was different from yours, but updating helped! 

I certainly received events in my apps! I'll scout things out with this issue tomorrow morning

For the time being, I have a hunch-hypothesis:
Can you try locking that thread until Adapty is activated? Just add `await` to `activate` call, so Adapty is activated before `addEventListener` is called.

**Comment by leons1767** [comment]
Hello @divanc 

Thank you for your time. I tried the following.

Upgraded Expo to SDK 48, and the result is the same as SDK 46. I downgraded it back to SDK 46 because of compatibility reason.

Moved the adapty.addEventListener() to the .then block of adapty.activate(), it doesn't work either.

Used await like you suggested, still not working.

Ran an apk preview build directly on device without expo start --dev-client. Also, not working.

**Comment by leons1767** [comment]
Hello @divanc 

Any update on the issue?

**Comment by leons1767** [comment]
Hello @divanc 

Is there a way to check the state of the listener, to know if it is even listening, or output the error of the listener?

When I set logLevel to 'verbose', and I could find 
```
[Adapty JS vUNKNOWN] — verbose: bridgeCall: Calling native method. SUCCESS
	methodName="activate"
	args="{\n  \"sdk_key\": \"***removed***\",\n  \"observer_mode\": false,\n  \"user_id\": \"***removed***\",\n  \"log_level\": \"verbose\"\n}"
```
follow by
```
[Adapty JS vUNKNOWN] — verbose: Adapty.addListener: Registering new listener
	event="onLatestProfileLoad"

```
but there is no response log, to suggest the registration is successful.

**Comment by divanc** [comment]
Hello again, @leons1767. Let me answer your questions, before I will be able to test Android Expo today

> Is there a way to check the state of the listener, to know if it is even listening, or output the error of the listener?

`addListener` would not send an event if there is an error, that you can find in your logs. While verbosing, there are only two `addListener` logs now:

1. `Registering new listener` meaning new listener is about to be added
2. `Failed to decode profile in event listener` error meaning native SDK sent an event with invalid body

> but there is no response log, to suggest the registration is successful. However, when I remove the listener, there seems to be one.

There is no log about successful listener registration as it does not throw. I'm currently studying how I can make verbose logs perfectly clear, so thanks for pointing out misunderstanding point.

**Comment by leons1767** [comment]
Thanks @divanc for taking time. Looking forward to hearing from you about the Android Expo test.

**Comment by divanc** [comment]
I can confirm, that events do not seem to be sent in Android with Expo SDK.

I've already fixed this issue locally and currently testing it, please stay tuned!

@leons1767

**Comment by divanc** [comment]
@leons1767 I've tested on latest Expo SDK, you seem to have the same version. Can you please try v2.4.3?

**Comment by leons1767** [comment]
@divanc Thank you very much for your work. I tried v2.4.3 with Expo SDK 46, and I confirm the listener is now receiving events.

**Comment by leons1767** [comment]
@divanc 

I'm sorry, but it seems that only the first listener is receiving events, when there are 2 registered listeners from 2 different devices. 

The use case is users logged on to two devices at the same time (hence two listeners, one listener per device), and only one device is receiving the event.

**Comment by divanc** [comment]
Oof, that is interesting case. Can you elaborate? 
Do you make a purchase and receive event only on the same device?

**Comment by leons1767** [comment]
@divanc Yes, Device 1 made a purchase and received the event on Device 1. When a subscription cancellation is made in Google Play Store on Device 1, Device 1 also received the subscription cancellation event. Device 2 received none of the events.  Both devices activated adapty using the same customerId, and subscribed to the listener the same way.

**Comment by leons1767** [comment]
Hello @divanc

Were you able to make some progress on the issue?

**Comment by divanc** [comment]
@leons1767, I'm very sorry for being absent. A load of priority task fell on me :(

I'm going to try double-sim tomorrow, but there is a part you need to know. 
addEventListener works momentarily only for the current device. If you have purchased on the device X, event should fire right after the successful modal (sometimes a little slow on sandboxes due to tons of history).

If you have purchased a product on device X and expecting device Y to fire update event that should happen by the following mechanism:

Adapty (if possible) fetches a profile info **once in a minute**, then compares two strings. If those are different, SDK fires an event. That should only mean, that other devices can have a slightly-delayed event resolution.

I've said all this without testing yet, let me return to you tomorrow

**Comment by leons1767** [comment]
Hello @divanc , thanks for the update and explanation about the event. I'm still following the issue, and hoping for a fix soon.

**Comment by divanc** [comment]
@leons1767 
I'm sorry, but I was unable to reproduce it with any scenario. Here is what I've tried

- Two apps open, one buys, second receives (on a video)
- Two apps open, one device is locked, unlocked after a purchase
- One app open, second opened in the midst of a purchase

Here is a video how it looks for all of my cases:
https://share.cleanshot.com/wX40fD8K

I'm sorry, but I'm gonna need to have some more data to discover the problem...

**Comment by leons1767** [comment]
Hello @divanc. 

Thank you for your time to try to reproduce the issue, I don't know what to say.

After updating to v2.4.6, I found the profile on the second device not getting updated even when the app restarted, I have to do adapty.restorePurchases() to get the latest profile (with the purchase from first device). I could see some events in the second device, the same event sent 3x, and they were not the latest event.

I'm letting this go, because even if I get it to work like simulated by you, there would be a significant delay between purchase and the listener receiving the event in the second device. I have done a workaround by writing the new expiryDate to an existing document that the devices are listening.

Again, thank you very much for your time.

**Comment by divanc** [comment]
Thank you! If you feel like this becomes bothersome, feel free to re-open!
