### ISSUE TITLE
SyntaxError: Unexpected token C in JSON at position 0

### ISSUE THREAD

**Issue by 15bedirhan** [adaptyteam/AdaptySDK-React-Native#6]
Hello,

I'm trying to make purchase with method makePurchase which is given in examples on doc. 
I'm getting this error SyntaxError: Unexpected token C in JSON at position 0.

you can see details below

  try {        
            const { purchaserInfo, product } = await adapty.purchases.makePurchase(product);
        }
        catch (error) { console.log('makePurchase error', error); }
    }

**Comment by Betra** [comment]
Hey! Sorry, haven't received a email for this ☹️
If problem persists can you provide a little more of an error text?

**Comment by divanc** [comment]
Hey, it's been more than a year since last message, I'll close this now. Feel free to re-open, if you still struggle
