### ISSUE TITLE
Issue about getProductsIntroductoryOfferEligibility

### ISSUE THREAD

**Issue by cheuchheang** [adaptyteam/AdaptySDK-React-Native#86]
### Description

Dear Adapty team,

I have a question regarding a new method that is just available in version 2.6.0 `getProductsIntroductoryOfferEligibility`.  I would you to use it to check if the users are eligible for the trial or not, but I faced the issue:
Following the doc, using  this line of code`adapty.getProductsIntroductoryOfferEligibility(products)`, it shows me the error as attached file. Could you check why this error happens?

Note: There are products with the trial and products without the trial 
in the paywall.

<img width="651" alt="code" src="https://github.com/adaptyteam/AdaptySDK-React-Native/assets/31935379/94b178a6-2eb4-4cec-98fd-4e56df5e7dd8">

![Simulator Screen Shot - iPhone 14 Pro - 2023-09-14 at 14 10 21](https://github.com/adaptyteam/AdaptySDK-React-Native/assets/31935379/b3cf21d0-baee-4d6f-bd2e-3d39d0187fbb)

**Comment by divanc** [comment]
Hey, @cheuchheang! How do you evaded pull request form? :D 
I can see it is iOS, I bet it is ios-only, and presumably not Expo

Can you tell me your RN version?

**Comment by divanc** [comment]
I just checked with our native dev team, we must not fire native callbacks twice, so this is not ok at all

Is this reproducible at your side? If yes, I will need your help!

We need verbose native logs to understand why function tries to return response two times.

That is done via:
1) When you call activate, set log level to verbose like:
```ts
await adapty.activate('MY_KEY', {
  logLevel: 'verbose',
});
```

2) Run your app via Xcode and open Xcode logs
3) Try to reproduce behavior and just export the log file. You might have some confidential data there, so it is best to send it to Adapty support and just say that you are the issue guy, they'll fetch me :)

**Comment by divanc** [comment]
I hope, your issue is resolved without our assistance by now, we will close issue and thoroughly check double responses possibilities. 

Please feel free to re-open if you still experience any problem like this
