### ISSUE TITLE
When __debugDeferActivation is true, get "The Adapty is not activated" !! 😤

### ISSUE THREAD

**Issue by bobwei** [adaptyteam/AdaptySDK-React-Native#87]
### Description

When __debugDeferActivation is true, get "The Adapty is not activated" !! 😤
Your SDK is really not friendly!!!! Considering changing to other alternatives!

### Version

2.6.0

### What platforms are you seeing the problem on?

iOS

### System info

```yml
[Error: #2002 (notActivated): The Adapty is not activated]
```

**Comment by divanc** [comment]
Yeah, you're right. Thank you very much for your report. I can see that my testing has lead to false positive results, because I mixed this key with a previous one

Soon we will release v2.6.1 with this problem fixed!

**Comment by radiodario** [comment]
After installing 2.7.0 we are seeing that `__debugDeferActivation` has no effect and we get the Sign in with Apple ID prompt on simulators on app boot (i.e. on calling `adapty.activate`)
